[package]
name = "linkura-cli"
version = "0.0.8"
edition.workspace = true
default-run = "linkura-cli"

[dependencies]
linkura-api.workspace = true
linkura-common.workspace = true
linkura-packet.workspace = true

anyhow.workspace = true
tokio.workspace = true
chrono.workspace = true
rust-i18n.workspace = true
clap.workspace = true
serde.workspace = true
serde_json.workspace = true
ctrlc.workspace = true
tracing.workspace = true

indicatif.workspace = true
inquire = "0.7.5"
colored = "3.0.0"

[[bin]]
name = "linkura-cli"
path = "src/main.rs"
